config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates_presence_of :name, :due_day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_url
    else
      render :action => :new
    end
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to task_path(@task)
    else
      render :action => :edit
    end
  end

  def destroy
    if Time.current <= @task.due_day
      @task.destroy
      flash[:notice] = "Task has been deleted!"
    else
      flash[:notice] = "Time expired, task cannot been deleted!"
    end

    redirect_to tasks_url
  end

  private 

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :due_day, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  We have some errors here!
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<% end %>

<div class="form container">
<%= form_for @task do |f| %>
  <div class="form-group">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :due_day, "Due day" %>
  <%= f.text_field :due_day, class: "form-control" %>  
  </div>
  <div class="form-group">
  <%= f.label :note, "Note" %>
  <%= f.text_area :note, class: "form-control" %>
  </div>
  <%= f.submit %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<%= render :partial => "form" %>

app/views/tasks/index.html.erb
<h1>To Do List</h1>
<table class="table table-striped table-condensed">
<% @tasks.each do |task| %>
  <tr>
      <td><%= task.name %></td>
      <td><%= link_to 'Detail', task_path(task) %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Delete', task_path(task), method: :delete, data:{ confirm: "Are you sure?" } %></td>
  </tr>  
  <% end %>
</ul>
</table>
<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<%= render :partial => "form" %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>

<p><strong>Due Day:</strong> <%= @task.due_day %></p>
<p><strong>Note:</strong></p>
<%= simple_format @task.note %>

<%= link_to 'Back to index', tasks_path %>